// Subset the display faces to Latin + Vietnamese, compress to woff2, and emit
// them as base64 data URIs in src/data/fonts.ts.
//
// Why inline: fetching the .ttf over Remotion's static server intermittently
// stalls a render worker past the delayRender timeout. A data URI has nothing
// to fetch, so font loading can never be the reason a render dies.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));

// Latin, Latin-1, Latin Extended A/B, combining marks and Latin Extended
// Additional — the last block is where Vietnamese tone marks actually live.
const UNICODES = [
  "U+0020-007E",
  "U+00A0-00FF",
  "U+0100-024F",
  "U+0300-0323",
  "U+1EA0-1EF9",
  "U+2013-2014",
  "U+2018-201D",
  "U+2022",
  "U+00B7",
  "U+20AB",
].join(",");

const FACES = [
  { family: "Baloo2", file: "Baloo2-ExtraBold.ttf", weight: "800" },
  { family: "BeVietnamPro", file: "BeVietnamPro-Black.ttf", weight: "900" },
  { family: "BeVietnamPro", file: "BeVietnamPro-SemiBold.ttf", weight: "600" },
];

const out = FACES.map(({ family, file, weight }) => {
  const src = `${root}public/fonts/${file}`;
  const dst = `${root}public/fonts/.tmp-${file}.woff2`;
  execFileSync("pyftsubset", [
    src,
    `--unicodes=${UNICODES}`,
    "--layout-features=*",
    "--flavor=woff2",
    `--output-file=${dst}`,
  ]);
  const b64 = readFileSync(dst).toString("base64");
  rmSync(dst);
  console.log(`${file}: ${(b64.length / 1024).toFixed(0)}KB base64`);
  return { family, weight, b64 };
});

mkdirSync(`${root}src/data`, { recursive: true });
writeFileSync(
  `${root}src/data/fonts.ts`,
  `// GENERATED by scripts/gen-fonts.mjs — do not edit by hand.\n` +
    `// Latin + Vietnamese subsets of the display faces, woff2, inlined as data URIs.\n` +
    `export type EmbeddedFont = { family: string; weight: string; url: string };\n\n` +
    `export const EMBEDDED_FONTS: EmbeddedFont[] = [\n` +
    out
      .map(
        (f) =>
          `  {\n    family: ${JSON.stringify(f.family)},\n    weight: ${JSON.stringify(
            f.weight
          )},\n    url: "data:font/woff2;base64,${f.b64}",\n  },`
      )
      .join("\n") +
    `\n];\n`
);
console.log("wrote src/data/fonts.ts");
