// Generate simplified country silhouette paths into src/data/maps.ts.
// Run once: `npm run gen:maps`. Output is committed so renders stay offline.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createRequire } from "node:module";
import { geoMercator, geoPath } from "d3-geo";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
const topo = JSON.parse(
  readFileSync(require.resolve("world-atlas/countries-50m.json"), "utf8")
);
const all = feature(topo, topo.objects.countries).features;

// name -> how many of the largest rings to keep (drops overseas territories,
// so the USA reads as the mainland and the UK as Britain + Ireland's north).
const WANT = [
  { key: "us", name: "United States of America", rings: 1, label: "MỸ" },
  { key: "fr", name: "France", rings: 1, label: "PHÁP" },
  { key: "de", name: "Germany", rings: 1, label: "ĐỨC" },
  { key: "gb", name: "United Kingdom", rings: 2, label: "ANH" },
  { key: "vn", name: "Vietnam", rings: 1, label: "VIỆT NAM" },
];

const BOX = 1000; // paths are generated into a 1000x1000 viewBox

const ringArea = (ring) => {
  let a = 0;
  for (let i = 0, n = ring.length - 1; i < n; i++) {
    a += ring[i][0] * ring[i + 1][1] - ring[i + 1][0] * ring[i][1];
  }
  return Math.abs(a / 2);
};

const out = WANT.map(({ key, name, rings, label }) => {
  const f = all.find((x) => x.properties.name === name);
  if (!f) throw new Error(`country not found: ${name}`);

  // Keep only the N largest polygons so islands/territories don't blow up the fit.
  let geometry = f.geometry;
  if (geometry.type === "MultiPolygon") {
    const kept = [...geometry.coordinates]
      .sort((a, b) => ringArea(b[0]) - ringArea(a[0]))
      .slice(0, rings);
    geometry = { type: "MultiPolygon", coordinates: kept };
  }

  const shape = { type: "Feature", geometry, properties: {} };
  const projection = geoMercator().fitExtent(
    [[BOX * 0.04, BOX * 0.04], [BOX * 0.96, BOX * 0.96]],
    shape
  );
  const d = geoPath(projection)(shape);

  // Bounding box of the projected shape, so callers can centre it precisely.
  const [[x0, y0], [x1, y1]] = geoPath(projection).bounds(shape);
  return { key, label, d, bbox: [x0, y0, x1 - x0, y1 - y0].map((n) => +n.toFixed(1)) };
});

mkdirSync(new URL("../src/data/", import.meta.url), { recursive: true });
writeFileSync(
  new URL("../src/data/maps.ts", import.meta.url),
  `// GENERATED by scripts/gen-maps.mjs — do not edit by hand.\n` +
    `// Source: world-atlas (Natural Earth 1:50m), Mercator-projected into a ${BOX}x${BOX} box.\n` +
    `export const MAP_BOX = ${BOX};\n\n` +
    `export type CountryMap = {\n  key: string;\n  label: string;\n  d: string;\n  bbox: [number, number, number, number];\n};\n\n` +
    `export const MAPS: Record<string, CountryMap> = {\n` +
    out
      .map(
        (m) =>
          `  ${m.key}: {\n    key: ${JSON.stringify(m.key)},\n    label: ${JSON.stringify(
            m.label
          )},\n    bbox: [${m.bbox.join(", ")}],\n    d: ${JSON.stringify(m.d)},\n  },`
      )
      .join("\n") +
    `\n};\n`
);
console.log("wrote src/data/maps.ts:", out.map((o) => `${o.key} (${o.d.length}b)`).join(", "));
