import React from "react";
import { EMBEDDED_FONTS } from "../data/fonts";

/**
 * Declares the display faces as plain CSS `@font-face` rules with woff2 data
 * URIs (generated by scripts/gen-fonts.mjs).
 *
 * Deliberately NOT the FontFace JS API: `loadFont`/`new FontFace().load()`
 * intermittently never resolved in this headless container, and since it holds
 * a delayRender handle that killed long renders at random frames. A data URI in
 * CSS has nothing to fetch, so the browser resolves it during style resolution
 * and no handle is needed. `font-display: block` guarantees the fallback face
 * is never painted.
 */
const CSS = EMBEDDED_FONTS.map(
  (f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: block;
  src: url(${f.url}) format('woff2');
}`
).join("\n");

export const FontStyles: React.FC = () => (
  <style dangerouslySetInnerHTML={{ __html: CSS }} />
);
